name: Build and Publish

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Commit built files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: build dist [skip ci]"
          file_pattern: |
            dist/**
          branch: main

