name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write   # behövs för release-steget senare om du vill ladda upp assets

jobs:
  build-and-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm ci

      - name: Build bundle
        run: npm run build

      - name: Validate with HACS
        uses: hacs/action@main
        with:
          category: "plugin"
          comment: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

