# .github/workflows/ci.yml
name: Build & Validate HACS

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build-and-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Build bundle
        run: npm run build

      - name: Validate HACS structure
        uses: hacs/action@main
        with:
          category: "plugin"

