name: Validate HACS

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  validate-hacs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate with HACS Action
        uses: hacs/action@main
        with:
          category: "Dashboard"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          comment: true

