name: Validate HACS

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  validate-hacs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: HACS validation
        uses: hacs/action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          category: dashboard
          pr_comment: true

