# .github/workflows/release.yml
name: Release

on:
  release:
    types: [published]

permissions:
  contents: write   # viktig

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install & build
        run: |
          npm ci
          npm run build

      - name: Upload bundle to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/pollenprognos-card.js
          asset_name: pollenprognos-card.js
          asset_content_type: application/javascript

